# file: docker-compose.yml
# description: This file provides a docker container running docker-dnsmasq.

version: '3.7'

networks:
  dnsmasq:
    name: 'dnsmasq'

services:
  dnsmasq:
    container_name: 'dnsmasq'
    build:
      context: '.'
    image: 'brav0charlie/docker-dnsmasq:latest'
    cap_add:
      - 'NET_ADMIN'
      # Adding NET_ADMIN capability is required for DHCP Server to function
    ports:
      - '53:53/udp'
      - '67:67/udp'
      - '68:68/udp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config:/etc/dnsmasq.d'
      - './log:/var/log/dnsmasq'
    networks:
      - 'dnsmasq'
