FROM alpine:edge
LABEL maintainer="Bill Clark <36345117+brav0charlie@users.noreply.github.com>"
LABEL github_url="https://github.com/brav0charlie/docker-dnsmasq"
LABEL org.opencontainers.image.source https://github.com/brav0charlie/docker-dnsmasq
LABEL org.opencontainers.image.description "A dnsmasq Docker container"

# Install dnsmasq
RUN apk --no-cache add dnsmasq=2.90-r3

# Expose ports: 53/tcp (DNS), 67/udp & 68/udp (DHCP)
EXPOSE 53/udp
EXPOSE 67/udp
EXPOSE 68/udp

# Start dnsmasq, write log items to container console
ENTRYPOINT ["dnsmasq", "-k"]
